feat: add allow list for privileged containers
go-vela/pkg-runtime pull request #62
Opened 2020-10-19 14:58 UTC by kneal

2020-10-20 19:59 UTC, JordanSussman commented on runtime/docker/container.go
> +		if strings.HasPrefix(ctn.Image, image) {
I think this should be further updated to hopefully prevent someone from maliciously creating a image that utilizes the same prefix.

```suggestion
		if strings.HasPrefix(ctn.Image, fmt.Sprintf("%s:", image) || ctn.Image == image
```

2020-11-02 18:48 UTC, kneal commented on runtime/docker/container.go
> +		if strings.HasPrefix(ctn.Image, image) {
Took a slightly different approach. Then suggested, I opened up the list of privileged images to leverage Docker's reference match functionality.
https://pkg.go.dev/github.com/docker/distribution/reference#FamiliarMatch

I think this will allow us to stay closer to Docker's preferred way to match image types which should allow the administrator to compose a list of acceptable images to be used for a privileged image.

2020-11-02 19:01 UTC, JordanSussman commented on runtime/docker/container.go
> +		if strings.HasPrefix(ctn.Image, image) {
> Took a slightly different approach. Then suggested, I opened up the list of privileged images to leverage Docker's reference match functionality.
> https://pkg.go.dev/github.com/docker/distribution/reference#FamiliarMatch
> 
> I think this will allow us to stay closer to Docker's preferred way to match image types which should allow the administrator to compose a list of acceptable images to be used for a privileged image.

Sounds good! Can you add some more tests that validate this updated function will resolve my concerns? e.g. the pattern of `docker.company.com/foo` does not match the image of `docker.company.com/foo/bar`.

2020-11-02 19:26 UTC, kneal commented on runtime/docker/container.go
> +		if strings.HasPrefix(ctn.Image, image) {
Sure! I'll see if I can add that one in there!

2020-11-02 19:31 UTC, kneal commented on runtime/docker/container.go
> +		if strings.HasPrefix(ctn.Image, image) {
This commit I believe highlights the concern:
https://github.com/go-vela/pkg-runtime/pull/62/commits/363491db8c42a42179721eb709cb08164e0adfbc

So, in the test, we are expecting admin to have to allow listed: `docker.company.com/foo` with any tag available.

If a user tries to create and use `docker.company.com/foo/bar` that image on all tags would be blocked from getting the socket mount.

2020-11-03 21:28 UTC, JordanSussman commented on internal/image/image.go
> +	return false, nil
Could be further simplified to just:

```suggestion

	return match, nil
```

2020-11-03 21:50 UTC, JordanSussman commented on internal/image/image.go
> +// IsPrivledgedImage digests the provided image with a
Should replace all references of privledged with privileged.

2020-11-04 14:43 UTC, jbrockopp requested changes

2020-11-04 14:43 UTC, jbrockopp commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
I think you could simplify this function by using the functions we already created for parsing an image 👍

https://pkg.go.dev/github.com/go-vela/pkg-runtime/internal/image#ParseWithError

```suggestion
// privledged pattern to see if the image meets the criteria
// needed to allow a Docker Socket mount.
func IsPrivledgedImage(_image, privledged string) (bool, error) {
	// parse the image provided into a named, fully qualified canonical reference
	//
	// https://pkg.go.dev/github.com/go-vela/pkg-runtime/internal/image#ParseWithError
	_refImg, err := image.ParseWithError(_image)
	if err != nil {
		return false, err
	}
```

2020-11-04 14:43 UTC, jbrockopp commented on runtime/docker/container.go
> +		}
Have we double checked to see if this **only** works for the current container being executed?

Currently, we [create the host config (`c.hostConf`) once](https://github.com/go-vela/pkg-runtime/blob/master/runtime/docker/volume.go#L25-L26), and then reuse it for every container.

The way I'm reading the code, it looks like if the current image matches one from the list of privileged images, then we set the `Privileged` field in the host config to `true`.

Since we reuse the host config, I could see a scenario play out where step 1 in a pipeline references an image that is granted `privileged` access so the `Privileged` field in the host config is set to `true`.

Then step 2 in a pipeline references an image that **is not** granted `privileged` access but the `Privileged` field in the host config would still be set to `true` from the previous step (unless I'm missing the code that sets it to `false`).

2020-11-04 16:22 UTC, kneal commented on runtime/docker/container.go
> +		}
Let me check on that with some tests. That's a good question

2020-11-04 16:32 UTC, kneal commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
Yeah, I'm not sure I can without making it more complex or changing the return of that function.

In order to use [`FamiliarMatch`](https://pkg.go.dev/github.com/docker/distribution/reference#FamiliarMatch) I need a variable of type [`reference.Reference`](https://github.com/docker/distribution/blob/v2.7.1/reference/reference.go#L65) for the image. 

So, I could modify `ParseWithError` to return me something of that type but it felt easier to just re-use the Docker functions to parse the image.

2020-11-04 20:16 UTC, kneal commented on runtime/docker/container.go
> +		}
So, you're right about the Docker portion. Because of that config re-use, it would leverage the same config and give other containers elevated access. Got a local test that seems to look good where I just make a copy of the struct and pass that with the flag set for privileged. That will be in a new incoming commit. 

As far, as the Kubernetes implementation, that does appear to be scoped to each container that needs it. However, because of the way the Kubernetes runtime works were we pre-allocate all the containers in a pod. This does open up that elevated container, even more, to see all the contents in the other steps. This would only really happen in a breakout scenario. So, as long as the admin is locking down that image allow the list to images that are not like `alpine` they should be "okay". Not sure there is a way around that at this time since all the steps are run in a single pod but it is something to keep in mind.

2020-11-04 20:28 UTC, JordanSussman commented on runtime/docker/container.go
> +		}
> Not sure there is a way around that at this time since all the steps are run in a single pod but it is something to keep in mind.

Probably best to eventually add some documentation to further clarify the extra concerns of the privileged access when running within k8s.

2020-11-09 13:58 UTC, jbrockopp commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
Ahhh I see 👍 

I'm good with creating a custom function to accomplish this (`ParseRawWithError`?) and then use it in the `ParseWithError()` function?

Rough example:

```go
func ParseRawWithError(_image string) (reference.Reference, error) {
	// parse the image provided into a
	// named, fully qualified reference
	//
	// https://pkg.go.dev/github.com/docker/distribution/reference?tab=doc#ParseAnyReference
	_reference, err := reference.ParseAnyReference(_image)
	if err != nil {
		return _image, err
	}

	return _reference, nil
}
```

Otherwise, my only suggestion would be to update the original code for `reference.ParseNormalizedNamed()` to instead call `reference.ParseAnyReference()`.

```go
// privledged pattern to see if the image meets the criteria
// needed to allow a Docker Socket mount.
func IsPrivledgedImage(image, privledged string) (bool, error) {
	// parse the image provided into a
	// named, fully qualified reference
	//
	// https://pkg.go.dev/github.com/docker/distribution/reference?tab=doc#ParseAnyReference
	_refImg, err := reference.ParseAnyReference(image)
	if err != nil {
		return false, err
	}

	// add default tag "latest" when tag does not exist
	_refImg = reference.TagNameOnly(_refImg)
```

2020-11-09 14:21 UTC, kneal commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
I think I'd prefer to either add it to the existing function as a third return or do the second option you provided. So, adding it to existing would be like: 
```go
func ParseWithError(_image string) (string, string, error)
```

Then usage kinda reminds me of our [sdk](https://github.com/go-vela/sdk-go/blob/master/vela/build.go#L18) and calling the function would be like:

```go
image, raw, err := internal.ParseWithError(alpine:latest)`
```

Or with what you provided I would also need to call [`ParsedName`](https://pkg.go.dev/github.com/docker/distribution/reference#ParseNamed) to ensure I have the right data type to call -[`TagNameOnly`](https://pkg.go.dev/github.com/docker/distribution/reference#TagNameOnly)

2020-11-09 14:33 UTC, jbrockopp commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
What would be the value in adding it as a third return value vs creating a function specifically to handle this?

Typically in Go, messing with the function signature isn't (and shouldn't) be the first resort to handling a problem.

Especially for a function that is prominent like this one where it is used in quite a few spots throughout the `go-vela/pkg-runtime` codebase and that number will likely continue to grow 👍

2020-11-09 20:18 UTC, kneal commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
I agree with you changing the signature is not my first choice but I'm having a hard time seeing the value of a creating new function and making it public on the package when it's only used in the one location internal to the package.

2020-11-10 13:44 UTC, jbrockopp commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
Hmm... I think the value argument could be made both ways.

Anyways, moving on, I think that leaves us with changing the call to `reference.ParseAnyReference()` then?

2020-11-10 17:12 UTC, kneal commented on internal/image/image.go
> +	_refImg = reference.TagNameOnly(_refImg)
That works. I'll get this updated then 😄

2020-11-13 20:29 UTC, jbrockopp approved these changes
LGTM

2020-11-17 15:22 UTC, wass3r approved these changes

2020-11-17 15:23 UTC, merged